### ISSUE TITLE
Containerize me for 0.1 release 

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox-app-server#3]
For the 0.1 release, there will be no externally hosted cloud services. Instead, the container manager will start up a local version of databox-app-server pre-populated with the demo app and driver manifests. People will then be able to upload new manifests for apps they create to test locally.

**Comment by Toshbrown** [comment]
I like the simplicity of this approach for getting the 0.1 release out to the public. However, I also think that the 0.1 release should give a good overview of the whole ecosystem to new devs. The app store and registry are integral to the app development/deployment life cycle. I'm also not sure building in sideloading of apps on to the databox is a good plan, as it gives us another security headache.

I think that a solution with a local containerize registry and app store would be the best for 0.1. We could host the core images (arbiter + registry + demo apps) on docker hub so we do not have to host and secure the infrastructure. Then the local registry can be auto-populated with the core images from dockerhub at install or first launch. The container manager can then be modified to launch and use these at startup. If the installer then adds the required entries to the hosts file we would have a setup that mimics closely the intended architecture. Doing it this way also give us a fully working dev/test environment that can be used to develop any part of databox (arbitor/ app store etc), that is easily installable, isolated and usable offline after it has been installed. 

@mor1 @drdrmac @haddadi @cgreenhalgh do you have any preference on how this is solved for 0.1? 

 
P.S I like the suggestion that apps should be automatically built and deployed from the manifest, but I think this should be part of the app store (and approval process) rather than the Container manager post 0.1.

**Comment by dominicjprice** [comment]
The Vagrant file in the databox-vagrant repo could be a useful starting point for the v0.1 release as it currently wraps all dependencies including a containerised registry and app store. It shouldn't be hard to turn the Vagrantfile into an installation script.

**Comment by yousefamar** [comment]
> However, I also think that the 0.1 release should give a good overview of the whole ecosystem to new devs. The app store and registry are integral to the app development/deployment life cycle.

Exactly — the process of submitting apps to a store is likely going to be much different (not just a `docker push` and manifest upload). I don't think there's an advantage to having devs learn how to maintain a store, especially not the authentication and reviewing sides.

> I'm also not sure building in sideloading of apps on to the databox is a good plan, as it gives us another security headache.

So >0.1, our official app store should be the only place you can install apps from, assuming you're not developing? Maybe the others have thoughts on this too.

> I think that a solution with a local containerize registry and app store would be the best for 0.1. We could host the core images (arbiter + registry + demo apps) on docker hub so we do not have to host and secure the infrastructure. Then the local registry can be auto-populated with the core images from dockerhub at install or first launch. The container manager can then be modified to launch and use these at startup.

Is there an advantage to doing it this way than there is to pulling stuff straight to the host and launching it from there? Are there any functions that a registry covers that the host in itself cannot? When you say registry and "app store", do you mean an actual app store with accounts and all that, or just something that holds manifests?

> If the installer then adds the required entries to the hosts file we would have a setup that mimics closely the intended architecture.

:+1: 

> Doing it this way also give us a fully working dev/test environment that can be used to develop any part of databox (arbitor/ app store etc), that is easily installable, isolated and usable offline after it has been installed.

As would the above, no?

> P.S I like the suggestion that apps should be automatically built and deployed from the manifest, but I think this should be part of the app store (and approval process) rather than the Container manager post 0.1.

Completely agree, perhaps I didn't explain that bit very clearly. The dev submits only a manifest. It is built by the app store, and pushed to a registry (also from within the server), and made available on successful review. So only localhost can push to the registry.

The container manager, to install an app, gets a manifest, and (v0.1) installs it by name, defaulting to local Docker images, then DockerHub or potentially (>v0.1) registr[y|ies] listed in the manifest.

**Comment by yousefamar** [comment]
So to be clear, my argument is that both devs and users don't need to run an app store in the sense that they don't need to run a fully fledged store. They only really need to store manifest files, and that can literally just be a folder, or something through the dashboard to tell the CM where they are.

On the same note, having a local registry might be redundant, in the sense that for users, with a local registry, you would have this for what you described:

![registry](https://cloud.githubusercontent.com/assets/999235/20669560/c5c5577c-b56c-11e6-8a85-7129cea90b2b.png)

1. CM tells docker to run something
2. Docker sees that it's not installed, pulls it from DockerHub
3. Docker installs it locally
4. CM tells Docker to push it to registry container
5. Docker does it
6. CM tells Docker to launch app (maybe later)
7. Docker sees that it's already installed "locally", so it does

(You would download the same amount of stuff if the demo apps are already bundled with the version of the registry we put on DockerHub)

As opposed to:

![local](https://cloud.githubusercontent.com/assets/999235/20669559/c5c53a76-b56c-11e6-8d49-ffebc2d4e3f3.png)

1. CM tells docker to run something
2. Docker sees that it's not installed, pulls it from DockerHub
3. Docker installs it locally
4. CM tells Docker to launch app (maybe later)
5. Docker sees that it exists locally, so it does

And for developers:

![registry2](https://cloud.githubusercontent.com/assets/999235/20669558/c5c4cff0-b56c-11e6-9611-ad43190ec2dc.png)

1. Dev (or CM on being told by dev) builds app
2. App pushed to local registry (by dev or automatically by CM)
3. CM tells Docker to launch app (maybe later)
4. Docker sees that it's installed locally, so it does

(To really mirror behaviour of how it will be in production, the local app server would only accept source code, build it there, auto-approve for dev purposes, push it to registry, and then to run you pull it from there again. I think this would make the dev cycle much longer than it needs to be.)

Vs:

![local2](https://cloud.githubusercontent.com/assets/999235/20669562/c5c7f978-b56c-11e6-857c-af5084047205.png)

1. Dev (or CM on being told by dev) builds app
2. ~App pushed to local registry (by dev or automatically by CM)~
3. CM tells Docker to launch app (maybe later)
4. Docker sees that it's installed locally, so it does

Does that make sense?

Also I'm not convinced that devs should launch a full app store (maybe that's not what you meant anyway though). It would be equivalent to Apple devs running a sandbox App store server, or Android devs running a sandbox Google Play server locally.

**Comment by yousefamar** [comment]
Also just to elaborate on this "manifest as an entry-point" concept, this would make it so that registry and manifest server aren't two separate things that are implicitly linked. Instead, you only need to distribute manifests, and all the information about where the image is would be contained in there. But if eventually we only want one authoritative place where images can be gotten, then this would be redundant too. So the question is whether we want that.

**Comment by Toshbrown** [comment]
Let's talk later. The SDK will also require access to a registry if it is to run locally.

**Comment by haddadi** [comment]
I guess after today's call we are relatively clear on this for v0.1

**Comment by Toshbrown** [comment]
implemented in #4
